# Generated by Django 5.2.7 on 2025-10-23 17:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('identificador', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em Uso', 'Em Uso'), ('Substituido', 'Substituido')], default='Disponível', max_length=20)),
                ('motivo_substituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('identificador', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível'), ('Pendente', 'Pendente'), ('Pendente Devolução', 'Pendente Devolução')], default='Disponível', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('revenda', models.CharField(blank=True, choices=[('Revalle Juazeiro', 'Revalle Juazeiro'), ('Revalle Bonfim', 'Revalle Bonfim'), ('Revalle Petrolina', 'Revalle Petrolina'), ('Revalle Ribeira', 'Revalle Ribeira'), ('Revalle Paulo Afonso', 'Revalle Paulo Afonso'), ('Revalle Alagoinhas', 'Revalle Alagoinhas'), ('Revalle Serrinha', 'Revalle Serrinha')], max_length=100, null=True)),
                ('dominio', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_fisico', models.CharField(blank=True, max_length=150, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('licenca', models.CharField(blank=True, max_length=100, null=True)),
                ('anydesk', models.CharField(blank=True, max_length=50, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('potencia_nominal', models.CharField(blank=True, max_length=50, null=True)),
                ('autonomia_estimada', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_snmp', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_patrimonial', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('local_instalacao', models.CharField(blank=True, max_length=150, null=True)),
                ('poe', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True)),
                ('quantidade_portas', models.CharField(blank=True, max_length=10, null=True)),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_issued', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('peripherals', models.ManyToManyField(blank=True, related_name='equipment', to='inventory.peripheral')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('center_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True)),
                ('revenda', models.CharField(blank=True, max_length=100, null=True)),
                ('data_operacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.CharField(choices=[('Cadastro', 'Cadastro'), ('Empréstimo', 'Empréstimo'), ('Devolução', 'Devolução'), ('Edição', 'Edição'), ('Exclusão', 'Exclusão'), ('Estorno', 'Estorno'), ('Confirmação Empréstimo', 'Confirmação Empréstimo'), ('Confirmação Devolução', 'Confirmação Devolução'), ('Cadastro Periférico', 'Cadastro Periférico'), ('Vínculo Periférico', 'Vínculo Periférico'), ('Desvínculo Periférico', 'Desvínculo Periférico'), ('Substituição Periférico', 'Substituição Periférico')], default='Cadastro', max_length=30)),
                ('is_reversed', models.BooleanField(default=False)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('identificador', models.CharField(blank=True, max_length=100, null=True)),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('poe', models.CharField(blank=True, max_length=3, null=True)),
                ('quantidade_portas', models.CharField(blank=True, max_length=10, null=True)),
                ('operacao_anexo', models.FileField(blank=True, null=True, upload_to='anexos/operacoes/')),
                ('termo_assinado_anexo', models.FileField(blank=True, null=True, upload_to='anexos/termos/')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('peripheral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.peripheral')),
            ],
        ),
    ]
